### ISSUE TITLE
$stateProvider problem

### ISSUE THREAD

**Issue by yiludege** [PinkyJie/angular1-webpack-starter#14]
请教一个问题：
      看到把stateProvider包装到一个自己的Provider中，然后在run函数中就可以定义路由，顺带登录认证一起做了，感觉流程简单了不少。但是我直接run一个function A，A中inject[‘$stateProvider‘]，却会报错：Error: [$injector:unpr] Unknown provider: $stateProviderProvider <- $stateProvider。
      run不能注册provider这是事实，请问你的方式为什么可行呢？

**Comment by PinkyJie** [comment]
@yiludege run函数里面只能inject service，config函数里才可以inject provider，我的routeHelper是个service，而不是一个provider。我感觉你可能搞混service和provider的区别了，provider的$get函数返回的是一个service，`.provider('RouterHelper', RouterHelperProvider)`这句代码会同时注册一个名为`RouterHelperProvider`的provider和一个名为`RouterHelper`的service，注意第一个参数的名字为service的名字，这个名字后面加上`Provider`就是它注册的provider的名字。不知道这样讲是否清楚？

**Comment by yiludege** [comment]
非常清楚，感谢耐心解答！
