### ISSUE TITLE
npm install 就报错了

### ISSUE THREAD

**Issue by MEEllis** [PinkyJie/angular1-webpack-starter#15]

**Comment by PinkyJie** [comment]
dependence好久没更新了，报啥错能贴个图吗？

**Comment by hahaniu666** [comment]
![111](https://user-images.githubusercontent.com/19663312/28447584-2c6bd24e-6e04-11e7-9d76-2606fe4f725b.jpg)

**Comment by hahaniu666** [comment]
npm install 就会出现这个错  用npm update也不好使

**Comment by hahaniu666** [comment]
npm 6.11.0,npm 3.10.10

**Comment by PinkyJie** [comment]
你贴的图是webpack报的错把？
