### ISSUE TITLE
resolve problem

### ISSUE THREAD

**Issue by yiludege** [PinkyJie/angular1-webpack-starter#16]
不好意思，又来麻烦了，请教一个问题：我没有使用你封装好的RouterHelper，而是采用普通的在config中配置自己的项目，但是在需要登录的界面使用一个`resolve:{ Login: ['LoginResolve', function(LoginResolve){return LoginResolve.login();}]}`这样的resolve，相比你的`{loginResolve: self.Resolve.login}`确实很丑，但是angular.config的resolve要注入service没有办法，结果竟然无法工作。

发现是`ResolveService.prototype.login.$inject = ['UserAPI', '$q'];`这个UserAPI和$q都没有注入进来。我修改了一下这个LoginResolve类，可以正常工作了：
```
class LoginResolve {
	constructor (UserAPI, $q){
		Object.assign(this, {UserAPI, $q});
	}
	login () {
		const self = this;
		if (self.UserAPI.isLoggedIn() !== true) {
			return self.UserAPI.checkLoggedInStatus()
				 .catch(_error);
		}

		function _error () {
			return self.$q.reject('requireLogin');
		}
	}
}
LoginResolve.$inject = ['UserAPI', '$q'];
```

为什么你采用`self.Resolve.login`就可以使用`login`的inject，而我采用`LoginResolve.login()`则必须将注入放到`LoginResolve`再通过login来使用，`LoginResolve.login()`不会触发login的依赖注入工作吗？非常感谢！

**Comment by PinkyJie** [comment]
你实现的`LoginResolve`和我的`ResolveService`是有区别的，下面是我原来的实现：

```javascript
class ResolveService {
    login (UserAPI, $q) {
        if (UserAPI.isLoggedIn() !== true) {
            return UserAPI.checkLoggedInStatus()
                .catch(_error);
        }

        function _error () {
            return $q.reject('requireLogin');
        }
    }
}

ResolveService.prototype.login.$inject = ['UserAPI', '$q'];

export default ResolveService;
```

我的`ResolveService`这个service本身是无任何依赖的，只是其中的`login`方法有依赖，注意看上面的`$inject`也是挂在`login`这个方法上的，因为route的resolve里的key对应的也通常是一个方法，在这个方法上注入依赖。再看你的实现：`resolve:{ Login: ['LoginResolve', function(LoginResolve){return LoginResolve.login();}]}`，这个resolve的key（Login）对应的方法里你注入的是一个`LoginResolve`的service，然后又去调这个service的方法，但你调`.login()`的时候没有传参数，所以导致失败。你搞迷糊的地方就是你认为这个时候会自动注入依赖，但这里并不是依赖注入，而是你手动在调用一个已注入的service（LoginResolve）里的一个方法（login）。而你修改以后，这个service本身有依赖，所以你的`LoginResolve`在注入的时候自动也注入了它自己的依赖，所以就成功了。

**Comment by yiludege** [comment]
经过你的讲解，非常明白，感谢！你的`{loginResolve: self.Resolve.login}`实际上将login当做service，所以能够自动注入，而我的`resolve:{ Login: ['LoginResolve', function(LoginResolve){return LoginResolve.login();}]}`只是注入了`LoginResolve`这个服务，`login()`确实只是方法不会注入依赖。我这个地方怎么写都无法将login当做服务让它自动注入依赖，蛋疼。
