### ISSUE TITLE
Error at npm run

### ISSUE THREAD

**Issue by mohamedaboelmagd** [PinkyJie/angular1-webpack-starter#18]
npm start

> angular1-webpack-starter@0.5.0 start /home/Desktop/github/angular1-webpack-starter
> webpack-dev-server --mock

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1237:14)
    at listen (net.js:1273:10)
    at net.js:1382:9
    at nextTickCallbackWith3Args (node.js:452:9)
    at process._tickCallback (node.js:358:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.8.0-51-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! angular1-webpack-starter@0.5.0 start: `webpack-dev-server --mock`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular1-webpack-starter@0.5.0 start script 'webpack-dev-server --mock'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular1-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --mock
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular1-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular1-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/Desktop/github/angular1-webpack-starter/npm-debug.log

**Comment by PinkyJie** [comment]
As the error indicates, `Error: listen EADDRINUSE 0.0.0.0:8080` means your 8080 port is in use
