### ISSUE TITLE
extract-text-webpack-plugin这个报错该怎么解决

### ISSUE THREAD

**Issue by hahaniu666** [PinkyJie/angular1-webpack-starter#19]
![3333](https://user-images.githubusercontent.com/19663312/28490017-30a3c3e4-6f03-11e7-9575-abe13cb15d30.jpg)

![2222](https://user-images.githubusercontent.com/19663312/28490014-23dae1b0-6f03-11e7-997c-5bf53ff708e6.jpg)

**Comment by PinkyJie** [comment]
这个我最近研究下，应该是版本升级带来的问题

**Comment by hahaniu666** [comment]
好的，麻烦了

**Comment by PinkyJie** [comment]
https://github.com/shama/stylus-loader/issues/115

**Comment by PinkyJie** [comment]
@hahaniu666 我更新了下，是stylus-loader的问题，你拉一下最新代码试试。我本地的环境是node 8和npm 5，是OK的。

**Comment by hahaniu666** [comment]
好的,可以了,麻烦了
